'use client';
import { useEffect, useState } from 'react';
import { getOpportunitySummary } from '@/lib/api';
import { CategorySelector } from './CategorySelector';
import { InsightCard } from './InsightCard';
import { Layers, Map, TrendingUp } from 'lucide-react';
export function OpportunityMapPanel() {
  const [category,setCategory]=useState('salon'); const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(false);
  useEffect(()=>{ setLoading(true); getOpportunitySummary(category).then(setData).finally(()=>setLoading(false)); },[category]);
  const topCells=data?.top_cells||[]; const zones=data?.summary?.zone_counts||[];
  return <div className="grid gap-6 xl:grid-cols-[380px_1fr]"><aside className="space-y-5"><div className="rounded-3xl border border-white/10 bg-slate-950/70 p-5 backdrop-blur"><p className="text-xs uppercase tracking-[0.25em] text-emerald-300">Opportunity Map</p><h1 className="mt-3 text-3xl font-semibold text-white">Discover where business gaps exist.</h1><p className="mt-3 text-sm leading-6 text-slate-400">Select a category and explore high-demand, underserved, saturated, and emerging zones.</p><div className="mt-5"><CategorySelector value={category} onChange={setCategory}/></div></div><div className="grid gap-3">{zones.map((z:any)=><div key={z.label} className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[0.04] px-4 py-3"><span className="text-sm text-slate-300">{z.label}</span><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-sm text-emerald-200">{z.count}</span></div>)}</div></aside><main className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><InsightCard title="Analysed cells" value={data?.summary?.total_cells??'—'} caption="Grid cells ranked for this category." icon={<Map size={20}/>}/><InsightCard title="Top signal" value="Gap" caption="Demand, access and supply pressure." icon={<TrendingUp size={20}/>}/><InsightCard title="Layers" value="8" caption="Demand, access, competition, welfare, POIs and roads." icon={<Layers size={20}/>}/></div><div className="relative min-h-[560px] overflow-hidden rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_20%_20%,rgba(16,185,129,0.30),transparent_30%),radial-gradient(circle_at_80%_30%,rgba(59,130,246,0.20),transparent_25%),linear-gradient(135deg,#020617,#0f172a)] p-6"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(255,255,255,.07)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.07)_1px,transparent_1px)] [background-size:32px_32px]"/><div className="relative z-10 grid gap-3 md:grid-cols-2 lg:max-w-3xl">{topCells.slice(0,6).map((cell:any,idx:number)=><div key={cell.grid_id||idx} className="rounded-2xl border border-white/10 bg-slate-950/70 p-4 backdrop-blur transition hover:-translate-y-1"><div className="flex items-center justify-between"><p className="font-medium text-white">{cell.name||cell.grid_id}</p><span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-xs text-emerald-200">{Math.round(cell.opportunity_gap_score||0)}</span></div><p className="mt-2 text-xs text-slate-400">{cell.zone_label}</p><p className="mt-3 text-sm leading-5 text-slate-300">{cell.recommended_action}</p></div>)}</div>{loading&&<div className="absolute inset-0 z-20 grid place-items-center bg-black/30 text-sm text-slate-200">Loading…</div>}</div></main></div>;
}
